{% set name = "meshio" %}
{% set version = "4.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b3fcfead9233b0bfa883b0eaa0734b0de1e9cf8aa6eca9d0e604bd892549604

build:
  noarch: python
  number: 0
  entry_points:
    - meshio-ascii = meshio._cli:ascii
    - meshio-binary = meshio._cli:binary
    - meshio-compress = meshio._cli:compress
    - meshio-convert = meshio._cli:convert
    - meshio-decompress = meshio._cli:decompress
    - meshio-info = meshio._cli:info
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - importlib_metadata
    - numpy
    - netCDF4
    - h5py

test:
  requires:
    - exdown
    - pytest
    - netCDF4
    - h5py
  source_files:
    - README.md
    - tests
  imports:
    - meshio
  commands:
    - meshio-ascii --help
    - meshio-binary --help
    - meshio-compress --help
    - meshio-convert --help
    - meshio-decompress --help
    - meshio-info --help
    - python -m pytest

about:
  home: https://github.com/nschloe/meshio
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  summary: I/O for various mesh formats

extra:
  recipe-maintainers:
    - nschloe
    - MuellerSeb
    - banesullivan
